### ISSUE TITLE
Ligação AC

### ISSUE THREAD

**Issue by jaldwt** [josemariaaraujo/ShellyDiverter#2]
Viva, 

Estou com algumas dúvidas em entender a parte das ligações.
Segui os passos e já consegui flashar o ESPhome e instalar o programa compilado. 
Já retirei a placa de relés e já fiz os bypasses, dessoldei a resistência 47k soldei a resistência de 22 Ohms. 
A dúvida surge nas ligações:
Na imagem 124248, tens o R+ a ligar ao terminal positivo do SSR, até aí tudo bem, mas depois tens R- ligado ao terminal negativo, mas este está em comum com a fase? 
Penso que estou a interpretar mal o circuito e precisava de umas luzes para conseguir avançar sem perder o Shelly.

Por fim, relativamente às pinças, tenho uns SCT013, para os utilizar basta mudar a resistência de 22Ohms ou mais vale comprar uma pinça nova com especificações semelhantes à tua?

Resta-me agradecer a ajuda. 
jaldwt

**Comment by josemariaaraujo** [comment]
> Na imagem 124248, tens o R+ a ligar ao terminal positivo do SSR, até aí tudo bem, mas depois tens R- ligado ao terminal negativo, mas este está em comum com a fase?

Entendeste perfeitamente! A alimentação interna do shelly usa a fase como referencia (=GND), e liga ao negativo do SSR. 
Por ser tão pequeno não tem alimentação isolada, é  preciso tratar todas as saídas do shelly como sendo AC.

> Por fim, relativamente às pinças, tenho uns SCT013, para os utilizar basta mudar a resistência de 22Ohms ou mais vale comprar uma pinça nova com especificações semelhantes à tua?

Não precisas trocar, pode ser preciso mudar a calibração, ou no limite trocar a resistência de 22Ohm, mas podes ligar como está para ver os resultados que não há qualquer risco. 
Já agora qual o modelo do SCT013, para dar uma vista de olhos às datasheet a ver se são assim tão diferentes?

**Comment by jaldwt** [comment]
Obrigado pelo feedback! 

> Entendeste perfeitamente! A alimentação interna do shelly usa a fase como referencia (=GND), e liga ao negativo do SSR.
Por ser tão pequeno não tem alimentação isolada, é preciso tratar todas as saídas do Shelly como sendo AC.<

Assim sendo, é preciso ter atenção a qual é o neutro e qual a fase? Ou é indiferente?

O SCT013 é da YHDC SCT013 100A:50mA, não tenho muito mais informação sobre ele, já o comprei há 6 anos no AliE.

Vou proceder à ligação e testar :)

**Comment by josemariaaraujo** [comment]
> Assim sendo, é preciso ter atenção a qual é o neutro e qual a fase? Ou é indiferente?

É indiferente. 

> O SCT013 é da YHDC SCT013 100A:50mA, não tenho muito mais informação sobre ele, já o comprei há 6 anos no AliE.

Com esse transformador até 30A não há problema. O ADE7953 aguenta no máximo 0.5V peak na entrada. RMS dá 
$\frac{0.5V}{\sqrt{2}}=0,353Vrms$ . O teu transformador tem um rácio 2000:1, a corrente máxima antes de saturar a entrada é
$\frac {0,353V}{22Ohm} * 2000 = 32A$

O que usei tem um rácio 3000:1. Se quiseres posso recalcular as constantes do ade7953.cpp para o teu transformador ou se quiseres alterar a resistência para poder medir correntes maiores.

**Comment by jaldwt** [comment]
Para amperagens maiores terei que colocar uma resistência mais pequena, certo?
Relativamente ao calculo, em que parte do código em que instrução é feito?
Se conseguires recalcular, seria perfeito.

**Comment by josemariaaraujo** [comment]
No ficheiro ade7953.cpp substitui as linhas 33 a 51 por:
```
void ADE7953::update() {
  if (!this->is_setup_)
    return;

  auto energy_buffer = &this->energy_buffer_ ;
  ADE_PUBLISH(energy_buffer, 1.0f);
  auto energy_diverted = &this->energy_diverted_ ;
  ADE_PUBLISH(energy_diverted, 1.0f);  
  auto active_power_a = this->ade_read_<int32_t>(0x0312);
  ADE_PUBLISH(active_power_a, 435.0f);    
  auto active_power_b = this->ade_read_<int32_t>(0x0313);
  ADE_PUBLISH(active_power_b, 435.0f);
  auto current_a = this->ade_read_<uint32_t>(0x031A);
  ADE_PUBLISH(current_a, 281010.0f);  
  auto current_b = this->ade_read_<uint32_t>(0x031B);
  ADE_PUBLISH(current_b, 281010.0f);
  auto voltage = this->ade_read_<uint32_t>(0x031C);
  ADE_PUBLISH(voltage, 26000.0f);
}
```
Estes são os valores base para um CT (transformador de corrente) de 2000:1 com uma resistência de 22 Ohm.
Tens aqui uma folha de cálculo para se quiseres fazer alterações: [Google Sheets](https://docs.google.com/spreadsheets/d/10r9y6UEH0_P3OAnRmqzOGrElQc8ZBHv0Mporhut8w8I/edit?usp=sharing)
O "calculated current factor" é a base inicial para calcular o "current_a" (os "_b" são iguals aos "_a"). Para calibrar (se tiveres como medir a corrente) alteras o current_a (no meu caso tive de aumentar um bocado), e a folha de cálculo dá-te o valor para o active_power.

> Para amperagens maiores terei que colocar uma resistência mais pequena, certo?

Correto, para um limite maior deves diminuir a resistência. Também incluí o cálculo na folha
