### ISSUE TITLE
Adopt custom component for Sonoff Dual R3 v2 with bl0939

### ISSUE THREAD

**Issue by eogmau** [josemariaaraujo/ShellyDiverter#3]
Hi Jose,
Hope you are well
How is the power diverter working for you if you are still using it?

I would like to adopt the custom component you have created for the Sonoff Dual R3 v2 which uses bl0939 Power Sensor instead of the ADE7953.
Can you point me in the right direction where to start and things I should take in consideration?

Thanks

**Comment by josemariaaraujo** [comment]
It's working great for almost 2 years, no problems at all, I didn't even found the need to upgrade to the latest codebase of EPSHome where some changes where made to the ADE7953 code.  As is sometimes said: "If it works don't fix it!"

I'm not familiar with the bl0939. What is great about the ADE7953 is that it has a IRQ pin that when correctly programmed to read the power each AC cycle, allowing for precise control and that was the basis of my code.

Another open source diverter with free documentation and helpfull community is https://github.com/pablozg/freeds/tree/PID , if I can remenber correctly it can be built for under 50€ and can interface directly with some inverters
